version: '3.1'
services:
  redis:
    container_name: redis
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis/data
    command: redis-server --appendonly yes

volumes:
  redis_data:


