version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.7-management
    hostname: qimiaschool-queue
    ports:
      - "5672:5672"  # AMQP bağlantı noktası
      - "15672:15672" # RabbitMQ yönetim paneli
    volumes:
      - ./containers/queue/data/:/var/lib/rabbitmq
      - ./containers/queue/log/:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: qschool
      RABBITMQ_DEFAULT_PASS: sa123
